package com.vamsisangam.androidexamples;

import android.app.ListActivity;
import android.content.Context;
import android.content.Intent;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ContextMenu;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ListView;
import android.widget.SimpleAdapter;
import android.widget.Toast;

import java.util.ArrayList;
import java.util.HashMap;

public class HomeActivity extends ListActivity {
    private ListView lv;
    private HashMap<Integer, Class<?>> activityMap = new HashMap<>();
    private Context context;
    private final int ACTIVITY_TODAY = 0,
                      ACTIVITY_SECOND = 1,
                      ACTIVITY_THIRD = 2,
                      ACTIVITY_FOURTH = 3,
                      ACTIVITY_FIFTH = 4,
                      ACTIVITY_DISCOUNT_CALCULATOR = 5,
                      ACTIVITY_COURSE_FEE = 6;
    private HomeActivity THIS;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        init();

        ArrayList<HomeActivityListItem> arr = new ArrayList<>();

        arr.add(new HomeActivityListItem("Today Activity", "Displays current time and clears it on user's request."));
        arr.add(new HomeActivityListItem("Second Activity", "Takes user input and displays it in this activity as toast. Demonstrates calling and Activity for result."));
        arr.add(new HomeActivityListItem("Third activity", "Displays factors of a number. Demonstrates that data is lost when phone's orientation is changed."));
        arr.add(new HomeActivityListItem("Fourth activity", "Displays factors of a number. Demonstrates how data can be stored to prevent data loss when phone's orientation is changed."));
        arr.add(new HomeActivityListItem("Fifth activity", "It is an empty activity which displays log messages to demonstrate the Lifecycle of an Activity."));
        arr.add(new HomeActivityListItem("Discount calculator", "Discount calculator calculates discount and is adaptable to screen's orientation."));
        arr.add(new HomeActivityListItem("Course Fee", "Course Fee calculates and displays the course fee as the user starts to change the options."));
        arr.add(new HomeActivityListItem("Age Calculator", "Displays DatePicker widget where you can input DOB and get your age displayed."));
        arr.add(new HomeActivityListItem("Display Custom Toast", "Displays toast with a cool icon and text!"));
        arr.add(new HomeActivityListItem("Display Notification alert!", "Displays single and multiple notifications on button click, with and without delay."));
        arr.add(new HomeActivityListItem("Dialogs Demo Activity", "Displays all kinds of dialogs, example Alert Dialog and DatePicker Dialog."));
        arr.add(new HomeActivityListItem("Timer App!", "Set time, and hit Start! You can stop the time midway if you want to!"));
        arr.add(new HomeActivityListItem("Birthday Calculator", "Know how many days are left for your birthday! Just give your DOB and tadaaa!!"));
        arr.add(new HomeActivityListItem("User Preferences", "Set your user preferences. The layout is automatically generated by Android itself!"));
        arr.add(new HomeActivityListItem("Read/Write User Preferences", "Reads and writes user preferences from a custom .xml file. The layout is not generated and the code to read/write to preferences XML file is manually written."));
        arr.add(new HomeActivityListItem("Calculate sum of first N numbers", "Calculates the sum of first N numbers in a slow manner using AsyncTask. Notifies user after sum has been calculated."));
        arr.add(new HomeActivityListItem("Sum of first N numbers", "Calculates the sum of first N numbers using a Service and an Intent Service. Sends a notification when done."));
        arr.add(new HomeActivityListItem("Sum of N numbers, by Bound Service!", "Calculates the sum of first N numbers using a BoundService."));
        arr.add(new HomeActivityListItem("Start ANY Activity!!", "Uses and implicit intent to start an activity based on given action/category/data."));
        arr.add(new HomeActivityListItem("Time Ticker Receiver Activity", "Registers a Broadcast receiver to TIME_TICKER programmatically. Logs a statement after each minute. We can create an Alarm App by using the TIME_TICKER action."));
        arr.add(new HomeActivityListItem("Custom Adapter Demo", "Demonstrates a custom adapter. Displays a company's name, logo and buttons to call the company and also to view its website."));

        ArrayList<HashMap<String, String>> data = new ArrayList<>();

        for (HomeActivityListItem item : arr) {
            HashMap<String, String> map = new HashMap<>();

            map.put("title", item.getTitle());
            map.put("description", item.getDescription());

            data.add(map);
        }

        SimpleAdapter adapter = new SimpleAdapter(
                this.getApplicationContext(),
                data,
                R.layout.activity_home_list_item,
                new String[]{"title", "description"},
                new int[] {R.id.homeListItemTitle, R.id.homeListItemDescription});

        lv.setAdapter(adapter);

        // Context Menu code
        registerForContextMenu(lv);
        // Enable App Icon Click -> How do we handle it? -> It is a part of Options Menu
        getActionBar().setHomeButtonEnabled(true);
    }

    private void init() {
        lv = this.getListView();
        context = this.getApplicationContext();
        THIS = this;

        activityMap.put(0, TodayActivity.class);
        activityMap.put(1, SecondActivity.class);
        activityMap.put(2, ThirdActivity.class);
        activityMap.put(3, FourthActivity.class);
        activityMap.put(4, FifthActivity.class);
        activityMap.put(5, DiscountCalculatorActivity.class);
        activityMap.put(6, CourseFeeActivity.class);
        activityMap.put(7, AgeCalculatorActivity.class);
        activityMap.put(8, CustomToastActivity.class);
        activityMap.put(9, NoticationDemoActivity.class);
        activityMap.put(10, DialogsDemoActivity.class);
        activityMap.put(11, TimerActivity.class);
        activityMap.put(12, BirthdayCalculatorActivity.class);
        activityMap.put(13, UserPreferencesActivity.class);
        activityMap.put(14, ReadWritePreferencesActivity.class);
        activityMap.put(15, AsyncTaskDemoActivity.class);
        activityMap.put(16, SumServiceActivity.class);
        activityMap.put(17, SumBoundServiceActivity.class);
        activityMap.put(18, ImplicitIntentDemoActivity.class);
        activityMap.put(19, TimerTickerReceiverActivity.class);
        activityMap.put(20, CustomAdapterActivity.class);

        lv.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> adapterView, View view, int i, long l) {
            Intent intent = new Intent(THIS, activityMap.get(i));

            if (activityMap.get(i) == SecondActivity.class) {
                startActivityForResult(intent, ACTIVITY_SECOND);
            } else {
                startActivity(intent);
            }
            }
        });
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode == ACTIVITY_SECOND) {
            if (resultCode == RESULT_OK) {
                String result = data.getStringExtra("name");
                Toast.makeText(this, "From SecondActivity - " + result, Toast.LENGTH_LONG).show();
            }
        }
    }

    @Override
    public void onCreateContextMenu(ContextMenu menu, View v, ContextMenu.ContextMenuInfo menuInfo) {
        MenuInflater inflater = getMenuInflater();
        inflater.inflate(R.menu.context_menu_home_activity, menu);
    }

    @Override
    public boolean onContextItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case R.id.contextMenuHomeDisplayToast:
                Toast.makeText(getApplicationContext(),
                        "Tap and hold on a view opens the context menu. Here, that view is the whole list view! Pretty awesome, isn't it?",
                        Toast.LENGTH_LONG).show();
                break;
            case R.id.contextMenuHomeDiscountCalculator:
                Intent intent = new Intent(this, DiscountCalculatorActivity.class);
                startActivity(intent);
                break;
            case R.id.contextMenuHomeAgeCalculator:
                // Intent intent causes error! Cascading of switch!
                intent = new Intent(this, AgeCalculatorActivity.class);
                startActivity(intent);
                break;
            case R.id.contextMenuHomeCloseApp:
                finish();
                break;
            default:
        }

        return super.onContextItemSelected(item);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater inflater = getMenuInflater();
        inflater.inflate(R.menu.options_menu_home_activity, menu);

        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                Intent intent = new Intent(getApplicationContext(), HomeActivity.class);

                intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);    // clears backstack
                startActivity(intent);

                break;
            case R.id.optionsMenuHomeDarkTheme:
                lv.setBackgroundColor(Color.LTGRAY);
                break;
            case R.id.optionsMenuHomeCyanTheme:
                lv.setBackgroundColor(Color.CYAN);
                break;
            case R.id.optionsMenuHomeExit:
                finish();
                break;
            default:
        }

        return super.onOptionsItemSelected(item);
    }
}
